### ISSUE TITLE
Unable to run moviemasher client-react on my local without docker through packages.

### ISSUE THREAD

**Issue by ghost** [moviemasher/moviemasher.js#42]
Hello, 
I am unable to run moviemasher client-react on my local without docker through varies required packages.

1. First I install packages through these commands:- 

-  npm i @moviemasher/moviemasher.js, 
- npm i @moviemasher/client-react, 
- [npm](url) i @moviemasher/theme-default

2. Then I added these lines of code in my project:-
![Image20221114140314](https://user-images.githubusercontent.com/64742246/201613269-aac0bc1f-a802-464f-8504-2196b864585a.png)

3. Tried to run it but I was getting the below errors.
![Image2](https://user-images.githubusercontent.com/64742246/201613910-a2ea5e71-ee36-4121-bf9f-5485a9d8f613.png)

4.   Then I changed the import path and run again but I was getting another errors as below:-
![Image3](https://user-images.githubusercontent.com/64742246/201614411-f58a741c-a42c-4926-b27a-96a950d6cb61.png)
![Image4](https://user-images.githubusercontent.com/64742246/201614418-fdaec54e-33b3-46ed-9eda-71baf3ad2ab5.png)

**There is no proper documentation to run it without docker. Can you please guide me with some documentation or tutorials.**

**Comment by syntropo** [comment]
Thanks for checking out Movie Masher - sorry you're experiencing compilation and runtime issues. Not sure why your editor supplied the path it did, but the import should probably just point to the module like the example in the [Client Developer Guide](https://moviemasher.com/docs/ClientDeveloper.html):

```javascript
import { ApiClient, Masher, MasherDefaultProps } from "@moviemasher/client-react"
```

The runtime issues are arising because the `ApiClient` component is being included but the server doesn't seem to be running - the initial request from the component is failing to return a valid JSON payload. If you're just testing out the client side, the easy fix is to simply remove this component to avoid making any requests. 

Running the server outside Docker is not documented because it requires certain FFmpeg features that don't come in the default binary supplied by fluent-ffmpeg. Supplying cross-platform binaries through the mechanisms that NPM provides is beyond the scope of Movie Masher since only LINUX is supported by the server at this juncture. Hence, Docker is used during development and testing to provide developers with a standard LINUX environment. 

That said, it's still possible to run the server on other platforms if you've got a proper build of FFmpeg. Here's an example ExpressJS application from _workspaces/example-express/host/server.js_ that launches the server on port 8572:

```javascript
const MovieMasherServer = require("@moviemasher/server-express")

const { Host } = MovieMasherServer
const options = { 
  port: 8572, host: '0.0.0.0', 
  api: { authentication: { type: 'basic' } } 
}
const host = new Host(options)
host.start()
```
You should be able to switch the port to 8570 and execute this script by whatever means you typically launch ExpressJS applications. Even without a custom FFmpeg build you should be able do everything short of rendering video files. 

If you already have a server application that you're trying to incorporate Movie Masher into, you might find it easier to just point the client there and then add support for the APIs. The `ApiClient` component accepts an `endpoint` prop object that describes the initial request that's made:

```javascript
const clientProps = { 
  endpoint: { 
    protocol: 'http',
    host: 'localhost',
    port: 8080,
    prefix: '/api',
  },
  children: <Masher { ...props } />
}
const apiClient = <ApiClient { ...clientProps } />
```

On the server side, you'll need to add the endpoint you've specified and return an [ApiServersResponse](https://moviemasher.com/docs/interface/ApiServersResponse.html), as described in the
[Server Developer Guide](https://moviemasher.com/docs/ServerDeveloper.html#API%20Server). In this response you can selectively enable other APIs, as well as override their endpoints to point to other parts of your application.

**Comment by ghost** [comment]
Hello, 
I still got the same errors after removing <ApiClient /> and using the same import you shared in the versions 5.1.1 and 5.1.0 :-

**import { ApiClient, Masher, MasherDefaultProps } from "@moviemasher/client-react"**

And if I changed the import path to this :-

**import { ApiClient, Masher, MasherDefaultProps } from "@moviemasher/client-react/esm/client-react"**

and then I was able to accessing the components but I was getting compilation errors in the source code which shared earlier.
![image](https://user-images.githubusercontent.com/64742246/202348290-d4729678-8e9e-46a0-9acb-a1d4d3ca78d1.png)

### When I tried the same in 5.0.6 and 5.0.3 versions and I found that I am able to see Masher in my localhost using the code which I shared earlier only I need to downgraded the respective versions according to the package.json:-
![image](https://user-images.githubusercontent.com/64742246/202349160-9d7cd92f-4f1e-4fa4-8b1f-887e71565d49.png)


`Can you please know me how I can access other tier or children components because If I tried to render anything inside the Masher component the code breaks. Please guide me with some documentation or tutorials.`

**Comment by syntropo** [comment]
It's been ages since I tried to bundle anything with webpack - rollup has been tested much more extensively. What does the compiled code actually look like? Does it contain the missing exports or not? 

There are so many configuration options that might produce problems like this, it's hard to know where to start. Have you tried compiling with as few optimizations as possible? Perhaps needed exports are actually being tree shaken  away? 

I probably won't be able to test out compiling with webpack for a week or two. Please feel free to share results of any further testing you're able to do.

**Comment by syntropo** [comment]
I believe I may have tracked down the problem here, or at least come up with a solution that is working using what seems to be typical TypeScript/Webpack settings...

The problem is in @moviemasher/client-react/package.json where the UMD module path is specified for the `browser` key. Changing the key to `main` seems to fix the problem in Webpack. 

Could you perhaps make that change to your local copy of the module in `node_modules` and then test out your build?

**Comment by ghost** [comment]
Hello @syntropo ,
**I tried the solution you shared but I am unable to run moviemasher client-react on my local without docker through varies required packages. As I previously shared that if I use the below import statement:-**
`import { ApiClient, Masher, MasherDefaultProps } from "@moviemasher/client-react"
`
**I found these errors:-**

![image](https://user-images.githubusercontent.com/64742246/203217175-b3021b7d-ab0e-4628-b155-f4dba5d416c7.png)

**And If I use the below import statement:-**

`import { ApiClient, Masher, MasherDefaultProps } from "@moviemasher/client-react/esm/client-react"`

**Atleast I can able to access the modules through packages but I faced another complition errors in the source code:-**

![image](https://user-images.githubusercontent.com/64742246/203217633-35bf54d2-d281-41a7-8f2d-57933e5fc5c4.png)

**I tried to take pull of the source code of version5.1.1 and tried the script that are in package,json but still not working.**


**But If I tried same in the version5.0.6 or downgrade versions. It is working fine for me as per the documentation. Please know me correct steps to run moviemasher version5.1.1 through packages or source code with or without docker.**


Below are the commands I used to install packages:-
npm i @moviemasher/moviemasher.js,
npm i @moviemasher/client-react,
[npm](https://github.com/moviemasher/moviemasher.js/issues/url) i @moviemasher/theme-default

**Comment by syntropo** [comment]
Making the change I suggested should have fixed the compilation error. Did you attempt to run webpack right after changing the key from `browser` to `main` in `node_modules/@moviemasher/client-react/package.json`? If it still reported that the package had no exports, could you please share your webpack configuration?

The second error you are getting seems to be a runtime error and not a compilation error. As I explained above, this is because you're not running a server to handle the requests the client is making. For now, I might suggest removing the `ApiClient` component from your application to avoid making requests altogether.
